version: '3.8'
services:
    mongo:
        image: mongo:latest
        container_name: dogami-mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=root-db
        volumes:
            - ./database:/data/db
        ports:
            - 27017:27017
        restart: always

        networks:
            - dogami
    
    my_app: 
        build: 
          context: .
          dockerfile: get-dog.Dockerfile
        container_name: dogami-tool
        ports: 
          - 8000:5000
        environment:
          - MONGO_HOST=dogami-mongo
        volumes:
          - ./dog_transaction/log_real_time:/app/dog_transaction/log_real_time
          - ./dog_transaction/log_history:/app/dog_transaction/log_history
        networks:
            - dogami

    send-data-email: 
        build: 
          context: .
          dockerfile: send-data-email.Dockerfile
        container_name: dogami-send-data-email
        ports: 
          - 9000:6000
        environment:
          - MONGO_HOST=dogami-mongo
        volumes:
          - ./process_data/logs:/app/process_data/logs
        networks:
            - dogami


networks:
  dogami:
    # Use a custom driver
    driver: bridge