version: '3.8'
services:
    mongo:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=root-db
        volumes:
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./database:/data/db
        ports:
            - 27017:27017
        restart: always
    

    my_app: 
        build: .
        ports: 
          - 8000:5000
        volumes:
          - ./dog_info:/app/dog_info
          - ./dog_transaction:/app/dog_transaction 


